# ---------------------------------------------------------------------------
# ALB Availability & Route53 Health Monitoring Template
# Maintainer:
#
# Description:
#   Creates CloudWatch alarms for ALB availability and maps the Zero-2XX alarm
#   to a Route53 Health Check for internal-only applications. Supports ALB
#   monitoring across Dev/Stage/Prod with minimal false positives.
#
# Notes:
#   - Inputs are CloudWatch metric *dimensions*, not ARNs.
#     • LoadBalancerDimension: app/<alb-name>/<id>
#     • TargetGroupDimension:  targetgroup/<tg-name>/<id>
#   - Safe for internal-only deployments (no public HTTP probe required).
#   - Route53 Health Check uses CloudWatch alarm mirroring (R1 design).
#   - FourXX % alarm includes a configurable minimum-traffic guard to avoid noise.
# ---------------------------------------------------------------------------

AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ALB availability monitoring for internal apps using CloudWatch + Route53 (via CloudWatch alarm).
  Inputs are the CloudWatch metric dimensions (not ARNs). Alarms: Target 5XX (sum),
  Unhealthy Hosts (max), Zero 2XX (sum; drives Route53 HC), 4XX Error Rate (% with min-traffic guard).

# ===================================================================
# Parameters
# ===================================================================
Parameters:

  # -------------------------------
  # Required identifiers
  # -------------------------------
  EnvironmentName:
    Type: String
    AllowedPattern: "^[a-z0-9-]+$"
    Description: Short identifier for the environment (e.g., dev, stage, prod)

  # IMPORTANT: These are CloudWatch metric *dimension* strings (not ARNs).
  #   Examples:
  #     LoadBalancerDimension: app/CF-dev-s3-alb/08bds3636casd
  #     TargetGroupDimension:  targetgroup/CF-dev2ui-dev-s3-tg/123abc456def789
  LoadBalancerDimension:
    Type: String
    Description: "CloudWatch dimension for the ALB (format: app/<name>/<id>)"

  TargetGroupDimension:
    Type: String
    Description: "CloudWatch dimension for the Target Group (format: targetgroup/<name>/<id>)"

  AlarmSNSTopicARN:
    Type: String
    Description: SNS topic ARN for alarm notifications

  # -------------------------------
  # Thresholds (override per env if needed)
  # -------------------------------
  Target5XXPerMinuteThreshold:
    Type: Number
    Default: 10
    Description: Sum of Target 5XX per 60s period to alarm on (burst detection)

  UnhealthyHostCountThreshold:
    Type: Number
    Default: 1
    Description: Number of unhealthy targets to trigger an alarm

  Zero2XXMinutes:
    Type: Number
    Default: 5
    Description: Minutes with no 2XX responses before alarming (black-hole detection)

  # ---- 4XX-rate related tuning ----
  FourXXRatePercentThreshold:
    Type: Number
    Default: 10
    Description: >
      4XX as a percent of total requests to alarm on (e.g., 10 = 10%).
      Set higher in lower environments to minimize noise.

  FourXXRateEvalPeriods:
    Type: Number
    Default: 3
    Description: >
      Evaluation periods (minutes) for sustained 4XX rate above threshold.

  MinRequestVolumeFor4XX:
    Type: Number
    Default: 50
    Description: >
      Minimum RequestCount per minute before evaluating 4XX percentage.
      Recommended defaults: Dev=100, Stage=50, Prod=25. Helps minimize false alerts on low traffic.

# ===================================================================
# Resources
# ===================================================================
Resources:

  # ---------------------------------------------------------
  # ALARMS — Application Load Balancer + Target Group
  # ---------------------------------------------------------

  Target5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-ALB-Target-5XX-High"
      AlarmDescription: >
        Backend application returning many 5XX responses (reachable but failing).
        Indicates app/runtime errors, dependency outages, or a bad deploy.
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerDimension
        - Name: TargetGroup
          Value: !Ref TargetGroupDimension
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: !Ref Target5XXPerMinuteThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions: [!Ref AlarmSNSTopicARN]

  UnhealthyHostsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-ALB-UnhealthyHosts"
      AlarmDescription: >
        One or more targets behind the ALB are failing health checks.
        The ALB may have reduced or zero capacity to serve traffic.
      Namespace: AWS/ApplicationELB
      MetricName: UnHealthyHostCount
      Dimensions:
        - Name: TargetGroup
          Value: !Ref TargetGroupDimension
        - Name: LoadBalancer
          Value: !Ref LoadBalancerDimension
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: !Ref UnhealthyHostCountThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: breaching
      AlarmActions: [!Ref AlarmSNSTopicARN]

  # Zero 2XX — chosen as the driver for Route53 HealthCheck (R1 design)
  Zero2XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-ALB-No-Successful-Requests"
      AlarmDescription: >
        No successful (2XX) responses for several minutes.
        Detects DNS/routing issues or total outage where requests are not succeeding.
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_2XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerDimension
        - Name: TargetGroup
          Value: !Ref TargetGroupDimension
      Statistic: Sum
      Period: 60
      EvaluationPeriods: !Ref Zero2XXMinutes
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      # Z1 behavior: quiet periods are not outages (missing/zero data -> not breaching)
      TreatMissingData: notBreaching
      AlarmActions: [!Ref AlarmSNSTopicARN]

  FourXXRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-ALB-4XX-Rate-High"
      AlarmDescription: >
        Client-error rate is high (4XX as a percentage of total requests).
        Includes a minimum-traffic guard to avoid false positives at low volume.
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: !Ref FourXXRateEvalPeriods
      Threshold: !Ref FourXXRatePercentThreshold
      TreatMissingData: notBreaching
      AlarmActions: [!Ref AlarmSNSTopicARN]
      Metrics:
        # Total requests per period (1 minute)
        - Id: req
          MetricStat:
            Metric:
              Namespace: AWS/ApplicationELB
              MetricName: RequestCount
              Dimensions:
                - Name: LoadBalancer
                  Value: !Ref LoadBalancerDimension
                - Name: TargetGroup
                  Value: !Ref TargetGroupDimension
            Period: 60
            Stat: Sum
          ReturnData: false

        # Total 4XX responses per period
        - Id: e4xx
          MetricStat:
            Metric:
              Namespace: AWS/ApplicationELB
              MetricName: HTTPCode_Target_4XX_Count
              Dimensions:
                - Name: LoadBalancer
                  Value: !Ref LoadBalancerDimension
                - Name: TargetGroup
                  Value: !Ref TargetGroupDimension
            Period: 60
            Stat: Sum
          ReturnData: false

        # Percentage expression with minimum-traffic guard:
        # If RequestCount >= MinRequestVolumeFor4XX -> (4XX / RequestCount) * 100
        # Else return 0 to avoid noisy alerts during low volume.
        - Id: rate
          Expression: "IF(FILL(req, 0) >= ${MinRequestVolumeFor4XX}, (e4xx / FILL(req, 0)) * 100, 0)"
          Label: "4XX Error Rate (%)"
          ReturnData: true

  # ---------------------------------------------------------
  # ROUTE53 HEALTH CHECK (R1) — Mirrors Zero2XXAlarm via CloudWatch
  # Works for internal-only apps (no public HTTP probe).
  # ---------------------------------------------------------
  Route53HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: CLOUDWATCH_METRIC
        CloudWatchAlarmName: !Ref Zero2XXAlarm
        CloudWatchAlarmRegion: !Ref AWS::Region
        InsufficientDataHealthStatus: Healthy
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-App-Availability-From-CW"

  # Optional visibility alarm on Route53 health status itself
  Route53HealthStatusAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-Route53-HealthCheck-Unhealthy"
      AlarmDescription: >
        Route53 health check (mirroring the Zero-2XX alarm) is Unhealthy.
      Namespace: AWS/Route53
      MetricName: HealthCheckStatus
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref Route53HealthCheck
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching
      AlarmActions: [!Ref AlarmSNSTopicARN]

# ===================================================================
# Outputs
# ===================================================================
Outputs:
  Route53HealthCheckId:
    Description: ID of the Route53 Health Check (mirrors Zero-2XX alarm)
    Value: !Ref Route53HealthCheck
