AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Alarms for RDS PostgreSQL (Memory Utilization, Disk Utilization, Total Connections) - tuned for Prod (db.r6i.8xlarge)

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: The RDS instance identifier
  AlarmSNSTopicARN:
    Type: String
    Description: ARN of the SNS topic for alarm notifications

# Memory Utilization Alarm
# What it does:
# Alerts when the database’s available memory (RAM) drops below 20%, meaning more than 80% of memory is in use.
# Why it matters:
# Low free memory can slow queries, increase disk reads, and cause performance degradation or connection timeouts. Catching it early helps prevent slowdowns and stability issues.
Resources:
  MemoryUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${DBInstanceIdentifier}-MemoryUtilization-High"
      AlarmDescription: "Triggers when estimated memory utilization exceeds 80% (FreeableMemory < 51.2 GB for db.r6i.8xlarge)"
      Namespace: AWS/RDS
      MetricName: FreeableMemory
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 54931274752   # 51.2 GiB free = 20% free on 256 GiB total
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmSNSTopicARN
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier

# Disk Utilization Alarm
# What it does:
# Alerts when less than 20% of the database’s storage space is free — essentially when the disk is over 80% full.
# Why it matters:
# If storage fills up, the database can stop accepting writes or crash. Monitoring this ensures there’s time to scale storage or clean up old data before it becomes critical.
  DiskUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${DBInstanceIdentifier}-DiskUtilization-High"
      AlarmDescription: "Triggers when free storage space drops below 20% (80% utilized). Adjust threshold if DB storage differs."
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      # Example threshold assuming 500GB allocated → 20% = 100GB free
      Threshold: 107374182400  # 100 GiB free
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmSNSTopicARN
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier

# Total Connections Alarm
# What it does:
# Alerts when active database connections exceed 50% of the PostgreSQL maximum (2,500 of 5,000).
# Why it matters:
# Too many connections can overload the database, causing slow responses or connection failures. This alarm helps detect growing load before it impacts users.
  TotalConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${DBInstanceIdentifier}-TotalConnections-High"
      AlarmDescription: "Triggers when total database connections exceed 50% of PostgreSQL max (2,500 of 5,000)."
      Namespace: AWS/RDS
      MetricName: DatabaseConnections
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 2500
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmSNSTopicARN
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
