AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog Portfolio and Product for ALB Scaling Alerts'

Parameters:
  PortfolioName:
    Type: String
    Default: "Monitoring Solutions"
    Description: "Name of the Service Catalog portfolio"
  
  ProductName:
    Type: String
    Default: "ALB Scaling Alerts"
    Description: "Name of the Service Catalog product"
  
  TemplateS3Bucket:
    Type: String
    Description: "S3 bucket containing the ALB alerts template"
  
  TemplateS3Key:
    Type: String
    Default: "service-catalog/alb-scaling-alerts.yaml"
    Description: "S3 key path to the ALB alerts template"

Resources:
  # IAM Role for Service Catalog Launch
  ServiceCatalogLaunchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "ServiceCatalog-ALB-Alerts-LaunchRole-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: servicecatalog.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSServiceCatalogServiceRolePolicy
      Policies:
        - PolicyName: ALBAlertsLaunchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:TagResource
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                  - events:TagResource
                  - events:UntagResource
                  - sns:GetTopicAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeTargetGroups
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                Resource: !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/SC-*"

  # Service Catalog Portfolio
  MonitoringPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: "Platform Engineering"
      Description: "Monitoring and alerting solutions for AWS resources"
      DisplayName: !Ref PortfolioName
      Tags:
        - Key: "Department"
          Value: "Platform Engineering"
        - Key: "Purpose"
          Value: "Monitoring"

  # Service Catalog Product
  ALBScalingAlertsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: !Ref ProductName
      Description: "Deploy CloudWatch alarms and EventBridge rules for ALB scaling events"
      Owner: "Platform Engineering Team"
      Distributor: "Platform Engineering"
      SupportDescription: "Contact Platform Engineering team for support"
      SupportEmail: "platform-engineering@company.com"
      SupportUrl: "https://wiki.company.com/monitoring"
      Tags:
        - Key: "Product"
          Value: "Monitoring"
        - Key: "Category"
          Value: "ALB"
      ProvisioningArtifactParameters:
        - Name: "v1.0"
          Description: "Initial version with CloudWatch alarms and EventBridge rules"
          Info:
            LoadTemplateFromURL: !Sub "https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Key}"

  # Associate Product with Portfolio
  ProductPortfolioAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref MonitoringPortfolio
      ProductId: !Ref ALBScalingAlertsProduct

  # Launch Role Constraint
  LaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId: !Ref MonitoringPortfolio
      ProductId: !Ref ALBScalingAlertsProduct
      RoleArn: !GetAtt ServiceCatalogLaunchRole.Arn

  # Template Constraint (optional - for parameter validation)
  TemplateConstraint:
    Type: AWS::ServiceCatalog::LaunchTemplateConstraint
    Properties:
      PortfolioId: !Ref MonitoringPortfolio
      ProductId: !Ref ALBScalingAlertsProduct
      Rules: |
        {
          "Rules": {
            "ValidateALBArn": {
              "Rule": {
                "Fn::And": [
                  {
                    "Fn::Contains": [
                      ["arn:aws:elasticloadbalancing"],
                      {"Ref": "LoadBalancerArn"}
                    ]
                  },
                  {
                    "Fn::Contains": [
                      ["loadbalancer/app/"],
                      {"Ref": "LoadBalancerArn"}
                    ]
                  }
                ]
              },
              "Assertions": [
                {
                  "Assert": {"Ref": "ValidateALBArn"},
                  "AssertDescription": "LoadBalancerArn must be a valid Application Load Balancer ARN"
                }
              ]
            }
          }
        }

Outputs:
  PortfolioId:
    Description: "Service Catalog Portfolio ID"
    Value: !Ref MonitoringPortfolio
    Export:
      Name: !Sub "${AWS::StackName}-PortfolioId"
  
  ProductId:
    Description: "Service Catalog Product ID"
    Value: !Ref ALBScalingAlertsProduct
    Export:
      Name: !Sub "${AWS::StackName}-ProductId"
  
  LaunchRoleArn:
    Description: "Service Catalog Launch Role ARN"
    Value: !GetAtt ServiceCatalogLaunchRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LaunchRoleArn"
